version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "No build needed for static frontend"
      - ls -la frontend/

artifacts:
  files:
    - "**/*"
  base-directory: "frontend"
