AWSTemplateFormatVersion: "2010-09-09"
Description: "Photo Album Infrastructure V2 - Duplicate Resources for Testing"

Resources:
  # ============================================================
  # S3 BUCKETS (Version 2 - no conflict)
  # ============================================================

  FrontendBucketV2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-frontend-v2"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicyV2:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucketV2
      PolicyDocument:
        Statement:
          - Sid: AllowPublicRead
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucketV2.Arn}/*"

  StorageBucketV2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-storage-v2"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: ["GET", "PUT", "POST", "DELETE"]
            AllowedOrigins: ["*"]
            MaxAge: 3000

  StorageBucketPolicyV2:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorageBucketV2
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${StorageBucketV2.Arn}/*"

  # ============================================================
  # IAM ROLE (shared by both Lambda V2 functions)
  # ============================================================

  LambdaExecutionRoleV2:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-lambda-role-v2"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessV2
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${StorageBucketV2.Arn}"
                  - !Sub "${StorageBucketV2.Arn}/*"
        - PolicyName: RekognitionAccessV2
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - rekognition:DetectLabels
                  - rekognition:DetectFaces
                Resource: "*"

  # ============================================================
  # LAMBDA FUNCTIONS (Version 2)
  # ============================================================

  LF1IndexPhotosV2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-LF1-IndexPhotos-V2"
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRoleV2.Arn
      Timeout: 30
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucketV2
      Code:
        ZipFile: |
          # (same LF1 code as before)
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "LF1 V2 placeholder"}

  LF2SearchPhotosV2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-LF2-SearchPhotos-V2"
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRoleV2.Arn
      Timeout: 30
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucketV2
      Code:
        ZipFile: |
          # (same LF2 code as before)
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "LF2 V2 placeholder"}

  # ============================================================
  # API GATEWAY (Version 2)
  # ============================================================

  ApiGatewayV2:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-PhotoAlbumAPI-V2"

  ApiDeploymentV2:
    Type: AWS::ApiGateway::Deployment
    DependsOn: []
    Properties:
      RestApiId: !Ref ApiGatewayV2
      StageName: dev

  # ============================================================
  # PERMISSIONS
  # ============================================================

  LambdaPermissionLF1V2:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LF1IndexPhotosV2
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayV2}/*/*/*"

  LambdaPermissionLF2V2:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LF2SearchPhotosV2
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayV2}/*/*/*"

# ============================================================
# OUTPUTS
# ============================================================

Outputs:
  FrontendBucketV2Name:
    Value: !Ref FrontendBucketV2

  FrontendWebsiteV2URL:
    Value: !GetAtt FrontendBucketV2.WebsiteURL

  StorageBucketV2Name:
    Value: !Ref StorageBucketV2

  ApiV2URL:
    Value: !Sub "https://${ApiGatewayV2}.execute-api.${AWS::Region}.amazonaws.com/dev"

  LF1V2Name:
    Value: !Ref LF1IndexPhotosV2

  LF2V2Name:
    Value: !Ref LF2SearchPhotosV2
